### ISSUE TITLE
AttributeError: 'module' object has no attribute 'track'

### ISSUE THREAD

**Issue by dominis** [russss/Herd#28]
```
1d [:~/src/hacking] $ git clone git@github.com:russss/Herd.git
Cloning into 'Herd'...
remote: Counting objects: 317, done.
remote: Total 317 (delta 0), reused 0 (delta 0), pack-reused 317
Receiving objects: 100% (317/317), 396.80 KiB | 0 bytes/s, done.
Resolving deltas: 100% (149/149), done.
Checking connectivity... done.

1d [:~/src/hacking] $ cd Herd/

1d [:~/src/hacking/Herd] master ± python herd/herd.py
Traceback (most recent call last):
  File "herd/herd.py", line 13, in <module>
    import BitTornado.BT1.track as bttrack
  File "/Users/dominis/src/hacking/Herd/herd/BitTornado/BT1/track.py", line 4, in <module>
    from herd.BitTornado.parseargs import parseargs, formatDefinitions
  File "/Users/dominis/src/hacking/Herd/herd/herd.py", line 13, in <module>
    import BitTornado.BT1.track as bttrack
AttributeError: 'module' object has no attribute 'track'

1d [:~/src/hacking/Herd] master 1 ± python -v -m  herd/herd.py
...
import BitTornado # directory BitTornado
# BitTornado/__init__.pyc matches BitTornado/__init__.py
import BitTornado # precompiled from BitTornado/__init__.pyc
import BitTornado.BT1 # directory BitTornado/BT1
# BitTornado/BT1/__init__.pyc matches BitTornado/BT1/__init__.py
import BitTornado.BT1 # precompiled from BitTornado/BT1/__init__.pyc
# BitTornado/BT1/track.pyc matches BitTornado/BT1/track.py
import BitTornado.BT1.track # precompiled from BitTornado/BT1/track.pyc
/usr/bin/python: No module named BitTornado.parseargs
```

It's broken since 0ce81b869a60449cc1f5c0ac5c935cb97ad36a65 and I believe #22 is also related.

**Comment by AaronDMarasco-VSI** [comment]
If you still care, #29 might help.
